version: '3.1'

services:

  db:
   image: postgres
   restart: always
   ports:
     - "5432:5432"
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: example
   ports:
     - 5432:5432

  adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080

  nest:
   build: .
   volumes:
     - .:/nest
   ports:
     - 3000:3000
     - 9229:9229
   tty: true    

  database:
    image: 'mongo'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=mongo_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017-27019:27017-27019